- defaults:
    link:
        relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.vim: vim
    ~/.config/nvim: nvim
    ~/.tmux: tmux
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.bash_exports: bash/bash_exports
    ~/.bash_aliases: bash/bash_aliases
    ~/.bashrc: bash/bashrc
    ~/.fzf: fzf
    ~/.fzf.bash: bash/fzf.bash
    ~/.fzf.zsh: zsh/fzf.zsh
    ~/.jupyter/nbconfig/notebook.json: jupyter/notebook.json
    ~/.local/share/jupyter/nbextensions: jupyter/nbextensions
    ~/Library/Jupyter/nbextensions: jupyter/nbextensions
    ~/.zshrc: zsh/zshrc

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - >
        git cleanall -f
        jupyter/nbextensions
