# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/kevingreenman/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git colored-man-pages colorize pip python brew osx zsh-completions zsh-syntax-highlighting)
autoload -U compinit && compinit
  
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#

alias e="emacs"
alias v="vim"
alias jn="jupyter notebook"
alias ls="ls -G"
alias oa="open -a"
alias vzr="vim ~/.zshrc"
alias szr=". ~/.zshrc"
alias julia="exec '/Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia'"

# Accessing Remote Machines
alias athena="ssh kpg@athena.dialup.mit.edu"
alias eng4="ssh -F $HOME/.ssh/eofe-cluster/linux/config eofe4.mit.edu"
alias eng5="ssh -F $HOME/.ssh/eofe-cluster/linux/config eofe5.mit.edu"
alias eng7="ssh -F $HOME/.ssh/eofe-cluster/linux/config eofe7.mit.edu"
alias deep="ssh kpg@deepware.mit.edu"
alias lamb="ssh kpg@lambdamat.mit.edu"
alias rlamb="ssh -R 52623:localhost:52623 kpg@lambdamat.mit.edu"
alias hart="ssh kpg@hartree.mit.edu"
alias fock="ssh kpg@fock.mit.edu"
alias super="ssh kgreenman@txe1-login.mit.edu"
alias rmg="ssh kpg@rmg.mit.edu"
alias pharos="ssh kpg@pharos.mit.edu"
alias rain="ssh -Y kpg@rainier.mit.edu"
alias matt="ssh -Y kpg@matterhorn.mit.edu"
alias xsede="ssh kpg1@login.xsede.org"
alias comet="ssh kpg1@comet.sdsc.xsede.org"
alias satori="ssh kpg@satori-login-001.mit.edu"
alias satori-xfer="ssh kpg@satori-login-002.mit.edu"
alias cori="ssh kpgreenm@cori.nersc.gov"

fpath=(/usr/local/share/zsh-completions $fpath)

eval "$(pyenv init -)"

#export PATH="/Users/kevingreenman/.pyenv/versions/anaconda2-2019.07/bin:$PATH"
# export PATH="/Users/kevingreenman/.pyenv/versions/anaconda3-2019.10/bin:$PATH"  # commented out by conda initialize
export PATH="/Users/kevingreenman/.local/bin:$PATH"
export PATH="/Users/kevingreenman/.julia/bin:$PATH"

#export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export LSCOLORS=exfxfeaeBxxehehbadacea

bindkey -v

if [ -f  ~/.shell_local ]; then
    source ~/.shell_local
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPS="--extended"
