#!/bin/bash

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# vim aliases
# replaces vim by nvim if the latter exists
type nvim >/dev/null 2>&1 && {
    alias vim="nvim"
}
alias vzf="vim \$(fzf)"
alias v="vim"

# Python aliases
alias p="python3"
alias unittest="p -m unittest discover"


