#!/bin/bash
# Default editor
if command -v nvim > /dev/null
then
    export VISUAL=nvim
else
    export VISUAL=vim
fi
export EDITOR="$VISUAL"

export PROJECTSDIR="$HOME/projects"

# Personal projects
export HTVSDIR="$PROJECTSDIR/htvs"
export DJANGOCHEMDIR="$HTVSDIR/djangochem"
export MOLDOCKDIR="$PROJECTSDIR/moldocker"
export CLUSTER="$HOME/mnt/cluster"
export LOGDIR="$HOME/logs"
export NFF="$PROJECTSDIR/NeuralForceField"

export PYTHONPATH=$PROJECTSDIR:$HTVSDIR:$DJANGOCHEMDIR:$NFF:$MOLDOCKDIR:$PYTHONPATH
export MPLCONFIGDIR="$HOME/.config/matplotlib"

export PACKAGESDIR="$HOME/packages"
export DOTFILES="$PROJECTSDIR/dotfiles"
export DOTLOCAL="$PROJECTSDIR/dotfiles_local"

