#!/bin/bash

# Default editor
if command -v nvim > /dev/null
then
    export VISUAL=nvim
else
    export VISUAL=vim
fi
export EDITOR="$VISUAL"

# Fuzzy Finder
export FZF_DEFAULT_OPS="--extended"

# Personal projects
export PROJECTSDIR="$HOME"
export CHEMPROPDIR="$PROJECTSDIR/chemprop"
export SMILESDIR="$PROJECTSDIR/chemdata/smiles/fluodye"
export NOTEBOOKSDIR="$PROJECTSDIR/chemdata/notebooks/kpg"
export SCRIPTSDIR="$PROJECTSDIR/chemdata/scripts"
export HTVSDIR="$PROJECTSDIR/htvs"
export DJANGOCHEMDIR="$HTVSDIR/djangochem"
export CHEMCONFIGS="$HTVSDIR/chemconfigs"
export CLUSTER="$HOME/mnt/cluster"
export LOGDIR="$HOME/logs"
export NFF="$PROJECTSDIR/NeuralForceField"
export confgenpath="$HTVSDIR/confgen"

export PYTHONPATH=$HTVSDIR:$DJANGOCHEMDIR:$NFF:$PROJECTSDIR
export MPLCONFIGDIR="$HOME/.config/matplotlib"

export PACKAGESDIR="$HOME/packages"
export DOTFILES="$PROJECTSDIR/dotfiles"
export DOTLOCAL="$PROJECTSDIR/dotfiles_local"

export RUN_BASH_EXPORTS="yes"
