#!/bin/bash

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# vim aliases
# replaces vim by nvim if the latter exists
type nvim >/dev/null 2>&1 && {
    alias vim="nvim"
}
alias vzf="vim \$(fzf)"
alias v="vim"

# Python aliases
alias p="python3"
alias ptest="p -m unittest"
alias unittest="p -m unittest discover"

alias canceljobs="awk '{print \$1}' | xargs scancel"

prettyjson() {
    python -m json.tool "$1"
}

alias ppath='echo $PATH | tr ":" "\n"'

# Miscellaneous aliases

alias o="less"
alias e="emacs"
alias v="vim"
alias jn="jupyter notebook"
alias oa="open -a"
alias vzr="vim ~/.zshrc"
alias szr=". ~/.zshrc"
alias julia="exec '/Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia'"

# Accessing Remote Machines
alias flux="ssh kpgreenm@flux-login.arc-ts.umich.edu"
alias nersce="ssh kpgreenm@edison.nersc.gov"
alias nerscc="ssh kpgreenm@cori.nersc.gov"
alias nanoxfer="sftp kpgreenm@nanoHUB.org"
alias athena="ssh kpg@athena.dialup.mit.edu"
alias eng4="ssh -F $HOME/.ssh/eofe-cluster/linux/config eofe4.mit.edu"
alias eng5="ssh -F $HOME/.ssh/eofe-cluster/linux/config eofe5.mit.edu"
alias eng7="ssh -F $HOME/.ssh/eofe-cluster/linux/config eofe7.mit.edu"
alias deep="ssh kpg@deepware.mit.edu"
alias lamb="ssh kpg@lambdamat.mit.edu"
alias rlamb="ssh -R 52623:localhost:52623 kpg@lambdamat.mit.edu"
alias hart="ssh kpg@hartree.mit.edu"
alias fock="ssh kpg@fock.mit.edu"
alias super="ssh kgreenman@txe1-login.mit.edu"
alias rmg="ssh kpg@rmg.mit.edu"
alias pharos="ssh kpg@pharos.mit.edu"
alias rain="ssh -Y kpg@rainier.mit.edu"
alias matt="ssh -Y kpg@matterhorn.mit.edu"
alias xsede="ssh kpg1@login.xsede.org"
alias comet="ssh kpg1@comet.sdsc.xsede.org"

alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'

