#!/bin/bash
# Default editor
if command -v nvim > /dev/null
then
    export VISUAL=nvim
else
    export VISUAL=vim
fi
export EDITOR="$VISUAL"

# Personal projects
export PROJECTSDIR="$HOME/projects"
export HTVSDIR="$PROJECTSDIR/htvs"
export DJANGOCHEMDIR="$HTVSDIR/djangochem"
export CHEMCONFIGS="$HTVSDIR/chemconfigs"
export MOLDOCKDIR="$PROJECTSDIR/moldocker"
export CLUSTER="$HOME/mnt/cluster"
export LOGDIR="$HOME/logs"
export NFF="$PROJECTSDIR/NeuralForceField"
export GULPY="$PROJECTSDIR/gulpy"
export confgenpath="$HTVSDIR/confgen"

export DSKRC="$PROJECTSDIR/dskrc"
export DSK_PYTHON="$DSKRC/python/inits"

export PYTHONPATH=$HTVSDIR:$DJANGOCHEMDIR:$GULPY:$NFF:$MOLDOCKDIR:$DSK_PYTHON:$PROJECTSDIR
export MPLCONFIGDIR="$HOME/.config/matplotlib"

export PACKAGESDIR="$HOME/packages"
export DOTFILES="$PROJECTSDIR/dotfiles"
export DOTLOCAL="$PROJECTSDIR/dotfiles_local"

